; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @lshr_sub_const(i32 %x) {
; CHECK-LABEL: @lshr_sub_const(
; CHECK-NEXT:    [[S:%.*]] = add i32 [[X:%.*]], -3
; CHECK-NEXT:    [[R:%.*]] = lshr i32 64, [[S]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %s = sub i32 %x, 3
  %r = lshr i32 64, %s
  ret i32 %r
}

define i32 @from_sub_issue222281(i8 %x) {
; CHECK-LABEL: @from_sub_issue222281(
; CHECK-NEXT:    [[M:%.*]] = and i8 [[X:%.*]], 120
; CHECK-NEXT:    [[V:%.*]] = or disjoint i8 [[M]], -128
; CHECK-NEXT:    [[TZ:%.*]] = call range(i8 3, 8) i8 @llvm.cttz.i8(i8 [[V]], i1 true)
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i8 [[TZ]] to i32
; CHECK-NEXT:    [[S:%.*]] = add nsw i32 [[Z]], -3
; CHECK-NEXT:    [[R:%.*]] = lshr i32 64, [[S]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %m = and i8 %x, -8
  %v = or i8 %m, -128
  %tz = call i8 @llvm.cttz.i8(i8 %v, i1 true)
  %z = zext nneg i8 %tz to i32
  %s = sub nuw nsw i32 %z, 3
  %r = lshr i32 64, %s
  ret i32 %r
}

; Negative test: 64 << 28 overflows 32-bit integer, so this should NOT fold
define i32 @lshr_sub_overflow(i32 %x) {
; CHECK-LABEL: @lshr_sub_overflow(
; CHECK-NEXT:    [[S:%.*]] = add i32 [[X:%.*]], -28
; CHECK-NEXT:    [[R:%.*]] = lshr i32 64, [[S]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %s = sub i32 %x, 28
  %r = lshr i32 64, %s
  ret i32 %r
}
